# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: my-sls-rest
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  #The next 2 lines specify the python3.6 kernel lambda function in europe
  name: aws
  runtime: python3.6
  region: eu-central-1
  # This specify environment variables common to all the lambdas
  environment:
    # This will define an environment variable BUCKET with the name of the bucket created on line 68
    BUCKET:
      Ref: S3BucketState
  # This describes the permissions common to all the lambdas
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
          - "*"
# The package tells what should be included and excluded from the zip package
package:
  exclude:
    - venv/**
    - node_modules/**
# This is the configuration of the different lambda function we want to deploy
functions:
  # The user_get function will be triggered on a GET /user/{id} and will execute the user.get function
  user_get:
    handler: user.get
    events:
      - http:
          path: user/{id}
          method: GET
  # The user_post function will be triggered on a POST /user and will execute the user.post function
  user_post:
    handler: user.post
    events:
      - http:
          path: user
          method: POST
  # The user_delete function will be triggered on a DELETE /user/{id} and will execute the user.delete function
  user_delete:
    handler: user.delete
    events:
      - http:
          path: user/{id}
          method: DELETE
  # The user_put function will be triggered on a PUT /user/{id} and will execute the user.put function
  user_put:
    handler: user.put
    events:
      - http:
          path: user/{id}
          method: PUT
  # The user_list function will be triggered on a GET /user/list and will execute the user.list function
  user_list:
    handler: user.all
    events:
      - http:
          path: user/list
          method: GET

#This creates an s3 bucket
resources:
  Resources:
    S3BucketState:
      Type: AWS::S3::Bucket

# This is th custom config ...
custom:
  # ... for the serverless-python-requirements plugin
  pythonRequirements:
    dockerizePip: True

#This specify the plugins to use
plugins:
  - serverless-python-requirements
